kafka:
  bootstrap-servers: 10.65.67.162:9092,10.65.67.163:9092,10.65.67.164:9092
  producer:
    retries: 3
    batch-size: 32768
    linger: 1
  consumer:
    'enable.auto.commit': false
    'session.timeout': 3000
    'group.id': jcfwzt_zhiming_test_group
    'auto.offset.reset': earliest
    'max.poll.records': 500
    'thread.min': 3
    'thread.max': 10
msg:
  consumer:
    topic: mqp-hzm-test


